# Generated by Django 4.0.5 on 2022-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traineemodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_fname', models.CharField(max_length=50)),
                ('trainee_lname', models.CharField(max_length=50)),
                ('trainee_email', models.EmailField(max_length=50)),
                ('trainee_phone', models.IntegerField()),
                ('trainee_dob', models.DateTimeField()),
                ('trainee_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_fname', models.CharField(max_length=50)),
                ('trainer_lname', models.CharField(max_length=50)),
                ('trainer_email', models.EmailField(max_length=50)),
                ('trainer_phone', models.IntegerField()),
                ('trainer_dob', models.DateTimeField()),
                ('trainer_password', models.CharField(max_length=50)),
            ],
        ),
    ]
