# Generated by Django 4.0.5 on 2022-06-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_trainer_name', models.CharField(max_length=50)),
                ('add_student_name', models.CharField(max_length=50)),
                ('add_student_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_trainer_name', models.CharField(max_length=50)),
                ('works_work_assgin_date', models.DateTimeField()),
                ('works_subject', models.CharField(max_length=100)),
                ('works_question', models.TextField()),
                ('works_work_status', models.BooleanField(default=False)),
                ('works_student_name', models.CharField(max_length=50)),
                ('works_upload_date', models.DateTimeField()),
            ],
        ),
    ]
