# Generated by Django 4.0.5 on 2022-06-20 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_works_works_work_assgin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='works_work_assgin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 9, 57, 11, 541700)),
        ),
    ]
