# Generated by Django 4.0.5 on 2022-06-20 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_works_works_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='works_upload_date',
            field=models.DateTimeField(default=False),
        ),
        migrations.AlterField(
            model_name='works',
            name='works_work_assgin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 10, 21, 30, 18437)),
        ),
    ]
