# Generated by Django 4.0.5 on 2022-06-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_alter_works_works_work_assgin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='works_work_assgin_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
