# Generated by Django 4.0.5 on 2022-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_alter_works_works_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='works_upload_date',
            field=models.DateTimeField(null=True),
        ),
    ]
